### ISSUE TITLE
QCEW errors out when grabbing pre-2012

### ISSUE THREAD

**Issue by kastanis** [mikeasilva/blsAPI#13]
blsQCEW('Area', year='2006', quarter='a', area='53027') sends an error:

Error in file(file, "rt") : cannot open connection
In addition: Warning message:
In file(file, "rt") :
  URL 'https://data.bls.gov/cew/data/api/2006/a/area/53027.csv': status was '404 Not Found'

**Comment by mikeasilva** [comment]
This issue lies with the BLS and not with the R package.  @kastanis, you should contact them to determine why it is producing a 404.  Alternatively you can download the raw data from https://www.bls.gov/cew/datatoc.htm
