### ISSUE TITLE
minor update to apiDF

### ISSUE THREAD

**Issue by YourEconProf** [mikeasilva/blsAPI#16]
In the docs, you include apiDF to convert the resulting json into a data.frame, but for some data (I use the JOLTS report) there are additional fields than these four. Therefore, I added the [1:4] in the unlist call:

```apiDF <- function(data){
  df <- data.frame(year=character(),
                   period=character(),
                   periodName=character(),
                   value=character(),
                   stringsAsFactors=FALSE)
  
  i <- 0
  for(d in data){
    i <- i + 1
    df[i,] <- unlist(d[1:4])
  }
  df$value = as.numeric(df$value)
  return(df)
}
```

**Comment by mikeasilva** [comment]
@YourEconProf What are the JOLTS series you are pulling?

**Comment by YourEconProf** [comment]
Job Openings and Labor Turnover Survey: [https://www.bls.gov/jlt/](https://www.bls.gov/jlt/)

**Comment by mikeasilva** [comment]
df <- blsAPI('JTS00000000HIR', return_data_frame = T) returns a data frame without any issue.
