### ISSUE TITLE
How to use api version 2

### ISSUE THREAD

**Issue by elliottmorris** [mikeasilva/blsAPI#20]
Running the following is only returning 10 years worth of data, 2003 to 2007, instead of the full 20-year span that I should be getting by using API v2.0.

``` 
payload <- list('seriesid'=c('ENU010011051013'),
                    'startyear'=1998,
                    'endyear'=2018)
  
response <- blsAPI(payload = payload,api_version = 2,return_data_frame = T)
```

Are there commands for logging into version 2.0 that I am missing?

Thanks

**Comment by elliottmorris** [comment]
Closing this issue with the following success code:

```
payload <- list('seriesid'=c('ENU010011051013'),
                    'startyear'=1998,
                    'registrationKey' = API_Key,
                    'endyear'=2018)
  
response <- blsAPI(payload = payload,api_version = 2,return_data_frame = T)
```

**Comment by flare9x** [comment]
I tried the above: 

object 'API_Key' not found

I stored my API_Key in the apikey viable.

**Comment by flare9x** [comment]
It worked by: 

payload <- list('seriesid'=c('ENU010011051013'),
                    'startyear'=1998,
                    'registrationKey' = "your_api_key",
                    'endyear'=2018)
