### ISSUE TITLE
Pulling QCEW data for all areas

### ISSUE THREAD

**Issue by aniruhil** [mikeasilva/blsAPI#25]
Hi Mike;

Thanks for your work on building this great package!

Is there a way to use the API to pull QCEW data for all areas with a few lines of code? This could be for a specific quarter or the annual series for a single year or multiple years.  

As of now I have to download the compressed flat-files for a given year, and then run code to read each file before binding them together.  

thanks in advance!

Ani

**Comment by mikeasilva** [comment]
@aniruhil :  Glad you find the package useful.  The BLS API doesn't really allow this.  https://www.bls.gov/developers/api_signature_v2.htm gives some examples of pulling multiple series.  You have to specify the series that you want.  Consequently I think the flat file would be the easiest method.

**Comment by aniruhil** [comment]
Thanks @mikeasilva. I ended up writing a few lines of code to loop through the flat files and then bind them into a single data frame. Happy 2019!
