### ISSUE TITLE
Unknown SSL protocol error in connection to api.bls.gov:443 

### ISSUE THREAD

**Issue by kchurchwell** [mikeasilva/blsAPI#27]
I've seen several comments on this throughout the internet saying BLS now requires TLS 1.2 or higher.  I'm using Microsoft Azure Studio R.  Can someone point me to clear directions on how to modify?
Thanks!

**Comment by kchurchwell** [comment]
**Unknown SSL protocol error in connection to api.bls.gov:443 **

**Comment by mikeasilva** [comment]
This is an issue with your Azure environment and not with the package.
