### ISSUE TITLE
Plz create a tag for v0.2.1

### ISSUE THREAD

**Issue by bikeactuary** [mikeasilva/blsAPI#29]
Hi Mike - I notice when I install_github() your repo I get v0.2.1, but you only have a tag up to v0.2.0. I could use the tag so that I can fix that later version in a dockerfile - would you be able to push an updated tag for 0.2.1?

`install_github("mikeasilva/blsAPI@v0.2.1")`

Thx
Mike

**Comment by mikeasilva** [comment]
@bikeactuary I have added the tag
