### ISSUE TITLE
Consider adding BLS QCEW Open Data

### ISSUE THREAD

**Issue by hiles8500** [mikeasilva/blsAPI#5]
QCEW is a BLS program that offers employment and wage data by industry for every county, MSA, state, and the US.  Most QCEW data is not available through the standard API.   All of it for 2012-forward is available via QCEW Open Data.  See link below for R input code. 

[http://www.bls.gov/cew/doc/access/data_access_examples.htm](url)

**Comment by mikeasilva** [comment]
Thanks for the great suggestion @hiles8500! I have added a blsQCEW function that allows pulling data through the QCEW Open Data access.  I will be submitting an updated package to CRAN shortly, but you can get in from GitHub.
