### ISSUE TITLE
querying for multiple years but only getting a subset

### ISSUE THREAD

**Issue by jafflerbach** [mikeasilva/blsAPI#7]
I am in need of employment statistics (total number of people employed) per year from 1990 - 2016 for ME, RI, CT, MA, and NH. There doesn't seem to be an easy way to select for these states without manually querying the [website here](http://data.bls.gov/cgi-bin/dsrv?sm) and then saving the 5 series ids. Is there an easier way to select the series ids?

Also my code is returning only a subset of the years requested. It would also be nice if I could add a column with the state name without having to know off hand what seriesid correlates to what State.

My code:

```r

## Pull the data via the API. The 5 series ids were grabbed by manually querying the database via the website: http://data.bls.gov/cgi-bin/dsrv?sm
states <- list(
  'seriesid' = c('SMU09000000000000001','SMU23000000000000001','SMU25000000000000001','SMU33000000000000001','SMU44000000000000001'),
  'startyear' = 1990,
  'endyear' = 2016)

response <-blsAPI(states,2)
json <- fromJSON(response)

## Process results
apiDF <- function(data){
  df <- data.frame(year=character(),
                   period=character(),
                   periodName=character(),
                   value=character(),
                   stringsAsFactors=FALSE)
  
  i <- 0
  for(d in data){
    i <- i + 1
    df[i,] <- unlist(d)
  }
  return(df)
}

employment <- apiDF(json$Results$series[[1]]$data)
```

Looking at the resulting dataframe I only have a handful of the available years

```r
> unique(employment$year)
  [1] "1994" "1993" "1992" "1991" "1990" "1999" "1998" "1997" "1996" "1995"
```

It'd be great to have a column with the state name in addition to these columns:
```r
> head(employment)
  year period periodName value
1 1994    M12   December 442.1
2 1994    M11   November 444.4
3 1994    M10    October 441.5
4 1994    M09  September 439.5
5 1994    M08     August 437.2
6 1994    M07       July 429.5
```

**Comment by mikeasilva** [comment]
@jafflerbach,

Sorry for the delay.  I don't know if there is an easier way to select the series id's.  [http://www.bls.gov/help/hlpforma.htm](http://www.bls.gov/help/hlpforma.htm) is documentation on the series id's that might be useful.

To your subset of the years requested point, the BLS API limits the number of years returned by requests.  For example
```r

states <- list(
  'seriesid' = c('SMU09000000000000001','SMU23000000000000001','SMU25000000000000001','SMU33000000000000001','SMU44000000000000001'),
  'startyear' = 1990,
  'endyear' = 2016)
response <-blsAPI(states,2)
json <- fromJSON(response)
json$message
```
returns "Year range has been reduced to the system-allowed limit of 10 years."  I will incorporate the display of the API messages in the R console in the next release as that is not clear.

As for adding the state name I will have to give it more thought.  The API doesn't provide any information on the name of the geography.
