### ISSUE TITLE
blsQCEW not work

### ISSUE THREAD

**Issue by JiawenQi98** [mikeasilva/blsAPI#8]
I ran the sample code
`MichiganData <- blsQCEW('Area', year='2013', quarter='1', area='26000')`
But it not work, the error is:
blsQCEW: Missing parameter for area request.  The area, year and quarter parameters are needed.

**Comment by mikeasilva** [comment]
I have just resolved the issue and commited it to GitHub.  I have also submitted a new package to CRAN.
