### ISSUE TITLE
Multi-series query with return.data.frame=T gives same data for all series

### ISSUE THREAD

**Issue by benryan58** [mikeasilva/blsAPI#9]
I'm trying to pull multiple series at once using blsAPI(), and I get everything correct if I let it return the data as JSON. However, if I set return.data.frame equal to TRUE, all my series have the same values. 

I was able to fix this by writing a wrapper function that converts the JSON stream to data.frame format myself:

blsToDF <- function(bls_pull) {
  bls_json <- fromJSON(bls_pull)
  numseries = length(bls_json$Results$series$seriesID)

  for(i in 1:numseries) {
    ser <- bls_json$Results$series$seriesID[i]
    if (i==1) {
      df <- cbind(bls_json$Results$series$data[[i]][,1:4],seriesID=ser)
      next
    }

    df <- rbind(df,cbind(bls_json$Results$series$data[[i]][,1:4],seriesID=ser))
  }

 return(df)
}

**Comment by mikeasilva** [comment]
Thanks for point out this issue.  I have resolved it!
